/* collision.c generated by valac 0.12.0, the Vala compiler
 * generated from collision.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gsl/gsl_vector_double.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>


#define DARKCORE_TYPE_COLLISION (darkcore_collision_get_type ())
#define DARKCORE_COLLISION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_COLLISION, DarkcoreCollision))
#define DARKCORE_COLLISION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_COLLISION, DarkcoreCollisionClass))
#define DARKCORE_IS_COLLISION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_COLLISION))
#define DARKCORE_IS_COLLISION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_COLLISION))
#define DARKCORE_COLLISION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_COLLISION, DarkcoreCollisionClass))

typedef struct _DarkcoreCollision DarkcoreCollision;
typedef struct _DarkcoreCollisionClass DarkcoreCollisionClass;
typedef struct _DarkcoreCollisionPrivate DarkcoreCollisionPrivate;
typedef gsl_vector DarkcoreVector;
#define _gsl_vector_free0(var) ((var == NULL) ? NULL : (var = (gsl_vector_free (var), NULL)))
typedef struct _DarkcoreParamSpecCollision DarkcoreParamSpecCollision;

struct _DarkcoreCollision {
	GTypeInstance parent_instance;
	volatile int ref_count;
	DarkcoreCollisionPrivate * priv;
};

struct _DarkcoreCollisionClass {
	GTypeClass parent_class;
	void (*finalize) (DarkcoreCollision *self);
};

struct _DarkcoreParamSpecCollision {
	GParamSpec parent_instance;
};


static gpointer darkcore_collision_parent_class = NULL;

gpointer darkcore_collision_ref (gpointer instance);
void darkcore_collision_unref (gpointer instance);
GParamSpec* darkcore_param_spec_collision (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void darkcore_value_set_collision (GValue* value, gpointer v_object);
void darkcore_value_take_collision (GValue* value, gpointer v_object);
gpointer darkcore_value_get_collision (const GValue* value);
GType darkcore_collision_get_type (void) G_GNUC_CONST;
enum  {
	DARKCORE_COLLISION_DUMMY_PROPERTY
};
DarkcoreVector* darkcore_collision_closest_point_on_segment (DarkcoreCollision* self, DarkcoreVector* segment_1, DarkcoreVector* segment_2, DarkcoreVector* circle_position);
DarkcoreVector* darkcore_vector_new_copy (gsl_vector* vector);
DarkcoreVector* darkcore_vector_new_copy (gsl_vector* vector);
gdouble darkcore_vector_length (DarkcoreVector* self);
gint darkcore_vector_div_scalar (DarkcoreVector* self, gdouble val);
gdouble darkcore_vector_dot (DarkcoreVector* self, gsl_vector* vector);
DarkcoreVector* darkcore_vector_new (gsize n);
DarkcoreVector* darkcore_vector_new (gsize n);
gboolean darkcore_collision_circle_in_rectangle (DarkcoreVector* v1, DarkcoreVector* v2, DarkcoreVector* position, gdouble radius);
DarkcoreCollision* darkcore_collision_new (void);
DarkcoreCollision* darkcore_collision_construct (GType object_type);
static void darkcore_collision_finalize (DarkcoreCollision* obj);


DarkcoreVector* darkcore_collision_closest_point_on_segment (DarkcoreCollision* self, DarkcoreVector* segment_1, DarkcoreVector* segment_2, DarkcoreVector* circle_position) {
	DarkcoreVector* result = NULL;
	DarkcoreVector* _tmp0_ = NULL;
	DarkcoreVector* segment;
	DarkcoreVector* _tmp1_ = NULL;
	DarkcoreVector* point;
	gdouble _tmp2_;
	gdouble segment_length;
	DarkcoreVector* _tmp3_ = NULL;
	DarkcoreVector* segment_unit;
	DarkcoreVector* _tmp4_ = NULL;
	DarkcoreVector* projection_unit;
	gdouble _tmp5_;
	gdouble projection;
	DarkcoreVector* _tmp6_ = NULL;
	DarkcoreVector* _result_;
	DarkcoreVector* _tmp11_ = NULL;
	DarkcoreVector* projection_vector;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (segment_1 != NULL, NULL);
	g_return_val_if_fail (segment_2 != NULL, NULL);
	g_return_val_if_fail (circle_position != NULL, NULL);
	_tmp0_ = darkcore_vector_new_copy ((gsl_vector*) segment_1);
	segment = _tmp0_;
	gsl_vector_sub ((gsl_vector*) segment, (gsl_vector*) segment_2);
	_tmp1_ = darkcore_vector_new_copy ((gsl_vector*) circle_position);
	point = _tmp1_;
	gsl_vector_sub ((gsl_vector*) point, (gsl_vector*) segment_2);
	_tmp2_ = darkcore_vector_length (segment);
	segment_length = _tmp2_;
	if (segment_length <= 0) {
		result = NULL;
		_gsl_vector_free0 (point);
		_gsl_vector_free0 (segment);
		return result;
	}
	_tmp3_ = darkcore_vector_new_copy ((gsl_vector*) segment);
	segment_unit = _tmp3_;
	darkcore_vector_div_scalar (segment_unit, segment_length);
	_tmp4_ = darkcore_vector_new_copy ((gsl_vector*) point);
	projection_unit = _tmp4_;
	_tmp5_ = darkcore_vector_dot (projection_unit, (gsl_vector*) segment_unit);
	projection = _tmp5_;
	_tmp6_ = darkcore_vector_new ((gsize) 2);
	_result_ = _tmp6_;
	if (projection <= 0) {
		gdouble _tmp7_;
		gdouble _tmp8_;
		_tmp7_ = gsl_vector_get ((gsl_vector*) segment_1, (gsize) 0);
		gsl_vector_set ((gsl_vector*) _result_, (gsize) 0, _tmp7_);
		_tmp8_ = gsl_vector_get ((gsl_vector*) segment_1, (gsize) 1);
		gsl_vector_set ((gsl_vector*) _result_, (gsize) 1, _tmp8_);
		result = _result_;
		_gsl_vector_free0 (projection_unit);
		_gsl_vector_free0 (segment_unit);
		_gsl_vector_free0 (point);
		_gsl_vector_free0 (segment);
		return result;
	}
	if (projection >= segment_length) {
		gdouble _tmp9_;
		gdouble _tmp10_;
		_tmp9_ = gsl_vector_get ((gsl_vector*) segment_2, (gsize) 0);
		gsl_vector_set ((gsl_vector*) _result_, (gsize) 0, _tmp9_);
		_tmp10_ = gsl_vector_get ((gsl_vector*) segment_2, (gsize) 1);
		gsl_vector_set ((gsl_vector*) _result_, (gsize) 1, _tmp10_);
		result = _result_;
		_gsl_vector_free0 (projection_unit);
		_gsl_vector_free0 (segment_unit);
		_gsl_vector_free0 (point);
		_gsl_vector_free0 (segment);
		return result;
	}
	_tmp11_ = darkcore_vector_new_copy ((gsl_vector*) segment_unit);
	projection_vector = _tmp11_;
	gsl_vector_scale ((gsl_vector*) projection_vector, projection);
	gsl_vector_memcpy ((gsl_vector*) _result_, (gsl_vector*) projection_vector);
	gsl_vector_add ((gsl_vector*) _result_, (gsl_vector*) segment_1);
	result = _result_;
	_gsl_vector_free0 (projection_vector);
	_gsl_vector_free0 (projection_unit);
	_gsl_vector_free0 (segment_unit);
	_gsl_vector_free0 (point);
	_gsl_vector_free0 (segment);
	return result;
}


gboolean darkcore_collision_circle_in_rectangle (DarkcoreVector* v1, DarkcoreVector* v2, DarkcoreVector* position, gdouble radius) {
	gboolean result = FALSE;
	DarkcoreVector* _tmp0_ = NULL;
	DarkcoreVector* test;
	gdouble _tmp1_;
	gdouble _tmp2_;
	gdouble _tmp4_;
	gdouble _tmp5_;
	gdouble _tmp7_;
	gdouble _tmp8_;
	gdouble _tmp10_;
	gdouble _tmp11_;
	DarkcoreVector* _tmp13_ = NULL;
	DarkcoreVector* _result_;
	gdouble _tmp14_;
	g_return_val_if_fail (v1 != NULL, FALSE);
	g_return_val_if_fail (v2 != NULL, FALSE);
	g_return_val_if_fail (position != NULL, FALSE);
	_tmp0_ = darkcore_vector_new_copy ((gsl_vector*) position);
	test = _tmp0_;
	_tmp1_ = gsl_vector_get ((gsl_vector*) position, (gsize) 0);
	_tmp2_ = gsl_vector_get ((gsl_vector*) v1, (gsize) 0);
	if (_tmp1_ < _tmp2_) {
		gdouble _tmp3_;
		_tmp3_ = gsl_vector_get ((gsl_vector*) v1, (gsize) 0);
		gsl_vector_set ((gsl_vector*) test, (gsize) 0, _tmp3_);
	}
	_tmp4_ = gsl_vector_get ((gsl_vector*) position, (gsize) 0);
	_tmp5_ = gsl_vector_get ((gsl_vector*) v2, (gsize) 0);
	if (_tmp4_ > _tmp5_) {
		gdouble _tmp6_;
		_tmp6_ = gsl_vector_get ((gsl_vector*) v2, (gsize) 0);
		gsl_vector_set ((gsl_vector*) test, (gsize) 0, _tmp6_);
	}
	_tmp7_ = gsl_vector_get ((gsl_vector*) position, (gsize) 1);
	_tmp8_ = gsl_vector_get ((gsl_vector*) v1, (gsize) 1);
	if (_tmp7_ < _tmp8_) {
		gdouble _tmp9_;
		_tmp9_ = gsl_vector_get ((gsl_vector*) v1, (gsize) 1);
		gsl_vector_set ((gsl_vector*) test, (gsize) 1, _tmp9_);
	}
	_tmp10_ = gsl_vector_get ((gsl_vector*) position, (gsize) 1);
	_tmp11_ = gsl_vector_get ((gsl_vector*) v2, (gsize) 1);
	if (_tmp10_ > _tmp11_) {
		gdouble _tmp12_;
		_tmp12_ = gsl_vector_get ((gsl_vector*) v2, (gsize) 1);
		gsl_vector_set ((gsl_vector*) test, (gsize) 1, _tmp12_);
	}
	_tmp13_ = darkcore_vector_new_copy ((gsl_vector*) position);
	_result_ = _tmp13_;
	gsl_vector_sub ((gsl_vector*) _result_, (gsl_vector*) test);
	_tmp14_ = darkcore_vector_length (_result_);
	result = _tmp14_ < radius;
	_gsl_vector_free0 (_result_);
	_gsl_vector_free0 (test);
	return result;
}


DarkcoreCollision* darkcore_collision_construct (GType object_type) {
	DarkcoreCollision* self = NULL;
	self = (DarkcoreCollision*) g_type_create_instance (object_type);
	return self;
}


DarkcoreCollision* darkcore_collision_new (void) {
	return darkcore_collision_construct (DARKCORE_TYPE_COLLISION);
}


static void darkcore_value_collision_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void darkcore_value_collision_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		darkcore_collision_unref (value->data[0].v_pointer);
	}
}


static void darkcore_value_collision_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = darkcore_collision_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer darkcore_value_collision_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* darkcore_value_collision_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		DarkcoreCollision* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = darkcore_collision_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* darkcore_value_collision_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	DarkcoreCollision** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = darkcore_collision_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* darkcore_param_spec_collision (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	DarkcoreParamSpecCollision* spec;
	g_return_val_if_fail (g_type_is_a (object_type, DARKCORE_TYPE_COLLISION), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer darkcore_value_get_collision (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, DARKCORE_TYPE_COLLISION), NULL);
	return value->data[0].v_pointer;
}


void darkcore_value_set_collision (GValue* value, gpointer v_object) {
	DarkcoreCollision* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, DARKCORE_TYPE_COLLISION));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, DARKCORE_TYPE_COLLISION));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		darkcore_collision_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		darkcore_collision_unref (old);
	}
}


void darkcore_value_take_collision (GValue* value, gpointer v_object) {
	DarkcoreCollision* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, DARKCORE_TYPE_COLLISION));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, DARKCORE_TYPE_COLLISION));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		darkcore_collision_unref (old);
	}
}


static void darkcore_collision_class_init (DarkcoreCollisionClass * klass) {
	darkcore_collision_parent_class = g_type_class_peek_parent (klass);
	DARKCORE_COLLISION_CLASS (klass)->finalize = darkcore_collision_finalize;
}


static void darkcore_collision_instance_init (DarkcoreCollision * self) {
	self->ref_count = 1;
}


static void darkcore_collision_finalize (DarkcoreCollision* obj) {
	DarkcoreCollision * self;
	self = DARKCORE_COLLISION (obj);
}


GType darkcore_collision_get_type (void) {
	static volatile gsize darkcore_collision_type_id__volatile = 0;
	if (g_once_init_enter (&darkcore_collision_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { darkcore_value_collision_init, darkcore_value_collision_free_value, darkcore_value_collision_copy_value, darkcore_value_collision_peek_pointer, "p", darkcore_value_collision_collect_value, "p", darkcore_value_collision_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (DarkcoreCollisionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) darkcore_collision_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DarkcoreCollision), 0, (GInstanceInitFunc) darkcore_collision_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType darkcore_collision_type_id;
		darkcore_collision_type_id = g_type_register_fundamental (g_type_fundamental_next (), "DarkcoreCollision", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&darkcore_collision_type_id__volatile, darkcore_collision_type_id);
	}
	return darkcore_collision_type_id__volatile;
}


gpointer darkcore_collision_ref (gpointer instance) {
	DarkcoreCollision* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void darkcore_collision_unref (gpointer instance) {
	DarkcoreCollision* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		DARKCORE_COLLISION_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



