/* keystate.c generated by valac 0.12.0, the Vala compiler
 * generated from keystate.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define DARKCORE_TYPE_KEY_STATE (darkcore_key_state_get_type ())
#define DARKCORE_KEY_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_KEY_STATE, DarkcoreKeyState))
#define DARKCORE_KEY_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_KEY_STATE, DarkcoreKeyStateClass))
#define DARKCORE_IS_KEY_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_KEY_STATE))
#define DARKCORE_IS_KEY_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_KEY_STATE))
#define DARKCORE_KEY_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_KEY_STATE, DarkcoreKeyStateClass))

typedef struct _DarkcoreKeyState DarkcoreKeyState;
typedef struct _DarkcoreKeyStateClass DarkcoreKeyStateClass;
typedef struct _DarkcoreKeyStatePrivate DarkcoreKeyStatePrivate;

struct _DarkcoreKeyState {
	GObject parent_instance;
	DarkcoreKeyStatePrivate * priv;
};

struct _DarkcoreKeyStateClass {
	GObjectClass parent_class;
};

struct _DarkcoreKeyStatePrivate {
	gboolean _up;
	gboolean _down;
	gboolean _left;
	gboolean _right;
	gboolean _space;
};


static gpointer darkcore_key_state_parent_class = NULL;

GType darkcore_key_state_get_type (void) G_GNUC_CONST;
#define DARKCORE_KEY_STATE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DARKCORE_TYPE_KEY_STATE, DarkcoreKeyStatePrivate))
enum  {
	DARKCORE_KEY_STATE_DUMMY_PROPERTY,
	DARKCORE_KEY_STATE_UP,
	DARKCORE_KEY_STATE_DOWN,
	DARKCORE_KEY_STATE_LEFT,
	DARKCORE_KEY_STATE_RIGHT,
	DARKCORE_KEY_STATE_SPACE
};
DarkcoreKeyState* darkcore_key_state_new (void);
DarkcoreKeyState* darkcore_key_state_construct (GType object_type);
gboolean darkcore_key_state_is_up (DarkcoreKeyState* self);
gboolean darkcore_key_state_get_up (DarkcoreKeyState* self);
void darkcore_key_state_set_up (DarkcoreKeyState* self, gboolean value);
gboolean darkcore_key_state_get_down (DarkcoreKeyState* self);
void darkcore_key_state_set_down (DarkcoreKeyState* self, gboolean value);
gboolean darkcore_key_state_get_left (DarkcoreKeyState* self);
void darkcore_key_state_set_left (DarkcoreKeyState* self, gboolean value);
gboolean darkcore_key_state_get_right (DarkcoreKeyState* self);
void darkcore_key_state_set_right (DarkcoreKeyState* self, gboolean value);
gboolean darkcore_key_state_get_space (DarkcoreKeyState* self);
void darkcore_key_state_set_space (DarkcoreKeyState* self, gboolean value);
static void darkcore_key_state_finalize (GObject* obj);
static void _vala_darkcore_key_state_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_darkcore_key_state_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


DarkcoreKeyState* darkcore_key_state_construct (GType object_type) {
	DarkcoreKeyState * self = NULL;
	self = (DarkcoreKeyState*) g_object_new (object_type, NULL);
	return self;
}


DarkcoreKeyState* darkcore_key_state_new (void) {
	return darkcore_key_state_construct (DARKCORE_TYPE_KEY_STATE);
}


gboolean darkcore_key_state_is_up (DarkcoreKeyState* self) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_up;
	return result;
}


gboolean darkcore_key_state_get_up (DarkcoreKeyState* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_up;
	return result;
}


void darkcore_key_state_set_up (DarkcoreKeyState* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_up = value;
	g_object_notify ((GObject *) self, "up");
}


gboolean darkcore_key_state_get_down (DarkcoreKeyState* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_down;
	return result;
}


void darkcore_key_state_set_down (DarkcoreKeyState* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_down = value;
	g_object_notify ((GObject *) self, "down");
}


gboolean darkcore_key_state_get_left (DarkcoreKeyState* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_left;
	return result;
}


void darkcore_key_state_set_left (DarkcoreKeyState* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_left = value;
	g_object_notify ((GObject *) self, "left");
}


gboolean darkcore_key_state_get_right (DarkcoreKeyState* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_right;
	return result;
}


void darkcore_key_state_set_right (DarkcoreKeyState* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_right = value;
	g_object_notify ((GObject *) self, "right");
}


gboolean darkcore_key_state_get_space (DarkcoreKeyState* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_space;
	return result;
}


void darkcore_key_state_set_space (DarkcoreKeyState* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_space = value;
	g_object_notify ((GObject *) self, "space");
}


static void darkcore_key_state_class_init (DarkcoreKeyStateClass * klass) {
	darkcore_key_state_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (DarkcoreKeyStatePrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_darkcore_key_state_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_darkcore_key_state_set_property;
	G_OBJECT_CLASS (klass)->finalize = darkcore_key_state_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_KEY_STATE_UP, g_param_spec_boolean ("up", "up", "up", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_KEY_STATE_DOWN, g_param_spec_boolean ("down", "down", "down", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_KEY_STATE_LEFT, g_param_spec_boolean ("left", "left", "left", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_KEY_STATE_RIGHT, g_param_spec_boolean ("right", "right", "right", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_KEY_STATE_SPACE, g_param_spec_boolean ("space", "space", "space", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void darkcore_key_state_instance_init (DarkcoreKeyState * self) {
	self->priv = DARKCORE_KEY_STATE_GET_PRIVATE (self);
	self->priv->_up = FALSE;
	self->priv->_down = FALSE;
	self->priv->_left = FALSE;
	self->priv->_right = FALSE;
	self->priv->_space = FALSE;
}


static void darkcore_key_state_finalize (GObject* obj) {
	DarkcoreKeyState * self;
	self = DARKCORE_KEY_STATE (obj);
	G_OBJECT_CLASS (darkcore_key_state_parent_class)->finalize (obj);
}


GType darkcore_key_state_get_type (void) {
	static volatile gsize darkcore_key_state_type_id__volatile = 0;
	if (g_once_init_enter (&darkcore_key_state_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DarkcoreKeyStateClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) darkcore_key_state_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DarkcoreKeyState), 0, (GInstanceInitFunc) darkcore_key_state_instance_init, NULL };
		GType darkcore_key_state_type_id;
		darkcore_key_state_type_id = g_type_register_static (G_TYPE_OBJECT, "DarkcoreKeyState", &g_define_type_info, 0);
		g_once_init_leave (&darkcore_key_state_type_id__volatile, darkcore_key_state_type_id);
	}
	return darkcore_key_state_type_id__volatile;
}


static void _vala_darkcore_key_state_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	DarkcoreKeyState * self;
	self = DARKCORE_KEY_STATE (object);
	switch (property_id) {
		case DARKCORE_KEY_STATE_UP:
		g_value_set_boolean (value, darkcore_key_state_get_up (self));
		break;
		case DARKCORE_KEY_STATE_DOWN:
		g_value_set_boolean (value, darkcore_key_state_get_down (self));
		break;
		case DARKCORE_KEY_STATE_LEFT:
		g_value_set_boolean (value, darkcore_key_state_get_left (self));
		break;
		case DARKCORE_KEY_STATE_RIGHT:
		g_value_set_boolean (value, darkcore_key_state_get_right (self));
		break;
		case DARKCORE_KEY_STATE_SPACE:
		g_value_set_boolean (value, darkcore_key_state_get_space (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_darkcore_key_state_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	DarkcoreKeyState * self;
	self = DARKCORE_KEY_STATE (object);
	switch (property_id) {
		case DARKCORE_KEY_STATE_UP:
		darkcore_key_state_set_up (self, g_value_get_boolean (value));
		break;
		case DARKCORE_KEY_STATE_DOWN:
		darkcore_key_state_set_down (self, g_value_get_boolean (value));
		break;
		case DARKCORE_KEY_STATE_LEFT:
		darkcore_key_state_set_left (self, g_value_get_boolean (value));
		break;
		case DARKCORE_KEY_STATE_RIGHT:
		darkcore_key_state_set_right (self, g_value_get_boolean (value));
		break;
		case DARKCORE_KEY_STATE_SPACE:
		darkcore_key_state_set_space (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



