/* sprite.c generated by valac 0.12.0, the Vala compiler
 * generated from sprite.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <GL/gl.h>
#include <SDL.h>


#define DARKCORE_TYPE_SPRITE (darkcore_sprite_get_type ())
#define DARKCORE_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_SPRITE, DarkcoreSprite))
#define DARKCORE_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_SPRITE, DarkcoreSpriteClass))
#define DARKCORE_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_SPRITE))
#define DARKCORE_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_SPRITE))
#define DARKCORE_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_SPRITE, DarkcoreSpriteClass))

typedef struct _DarkcoreSprite DarkcoreSprite;
typedef struct _DarkcoreSpriteClass DarkcoreSpriteClass;
typedef struct _DarkcoreSpritePrivate DarkcoreSpritePrivate;

#define DARKCORE_TYPE_ENGINE (darkcore_engine_get_type ())
#define DARKCORE_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_ENGINE, DarkcoreEngine))
#define DARKCORE_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_ENGINE, DarkcoreEngineClass))
#define DARKCORE_IS_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_ENGINE))
#define DARKCORE_IS_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_ENGINE))
#define DARKCORE_ENGINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_ENGINE, DarkcoreEngineClass))

typedef struct _DarkcoreEngine DarkcoreEngine;
typedef struct _DarkcoreEngineClass DarkcoreEngineClass;

#define DARKCORE_TYPE_TEXTURE (darkcore_texture_get_type ())
#define DARKCORE_TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_TEXTURE, DarkcoreTexture))
#define DARKCORE_TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_TEXTURE, DarkcoreTextureClass))
#define DARKCORE_IS_TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_TEXTURE))
#define DARKCORE_IS_TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_TEXTURE))
#define DARKCORE_TEXTURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_TEXTURE, DarkcoreTextureClass))

typedef struct _DarkcoreTexture DarkcoreTexture;
typedef struct _DarkcoreTextureClass DarkcoreTextureClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _DarkcoreTexturePrivate DarkcoreTexturePrivate;

typedef void (*DarkcoreSpriteDelegateType) (DarkcoreEngine* world, DarkcoreSprite* sprite, void* user_data);
struct _DarkcoreSprite {
	GObject parent_instance;
	DarkcoreSpritePrivate * priv;
	DarkcoreSpriteDelegateType on_key_press;
	gpointer on_key_press_target;
	GDestroyNotify on_key_press_target_destroy_notify;
	DarkcoreSpriteDelegateType on_render;
	gpointer on_render_target;
	GDestroyNotify on_render_target_destroy_notify;
	DarkcoreEngine* world;
};

struct _DarkcoreSpriteClass {
	GObjectClass parent_class;
};

struct _DarkcoreSpritePrivate {
	gdouble _x;
	gdouble _y;
	gdouble _rotation;
	gdouble _width;
	gdouble _height;
	guchar _color_r;
	guchar _color_g;
	guchar _color_b;
	gint _texture_index;
};

struct _DarkcoreTexture {
	GObject parent_instance;
	DarkcoreTexturePrivate * priv;
	SDL_Surface* surface;
	GLuint texture;
	GLenum texture_format;
	gint nOfColors;
	GLsizei texture_id;
	gint loaded;
	gint width;
	gint height;
};

struct _DarkcoreTextureClass {
	GObjectClass parent_class;
};


static gpointer darkcore_sprite_parent_class = NULL;

GType darkcore_sprite_get_type (void) G_GNUC_CONST;
GType darkcore_engine_get_type (void) G_GNUC_CONST;
#define DARKCORE_SPRITE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DARKCORE_TYPE_SPRITE, DarkcoreSpritePrivate))
enum  {
	DARKCORE_SPRITE_DUMMY_PROPERTY,
	DARKCORE_SPRITE_X,
	DARKCORE_SPRITE_Y,
	DARKCORE_SPRITE_ROTATION,
	DARKCORE_SPRITE_WIDTH,
	DARKCORE_SPRITE_HEIGHT,
	DARKCORE_SPRITE_COLOR_R,
	DARKCORE_SPRITE_COLOR_G,
	DARKCORE_SPRITE_COLOR_B,
	DARKCORE_SPRITE_TEXTURE_INDEX
};
DarkcoreSprite* darkcore_sprite_new (void);
DarkcoreSprite* darkcore_sprite_construct (GType object_type);
DarkcoreSprite* darkcore_sprite_new_from_file (DarkcoreEngine* world, const gchar* filename);
DarkcoreSprite* darkcore_sprite_construct_from_file (GType object_type, DarkcoreEngine* world, const gchar* filename);
gint darkcore_engine_addTexture (DarkcoreEngine* self, const gchar* filename);
void darkcore_sprite_set_texture_index (DarkcoreSprite* self, gint value);
DarkcoreSprite* darkcore_sprite_new_from_texture (DarkcoreEngine* world, gint texture_index);
DarkcoreSprite* darkcore_sprite_construct_from_texture (GType object_type, DarkcoreEngine* world, gint texture_index);
void darkcore_sprite_fire_key_press (DarkcoreSprite* self, DarkcoreSpriteDelegateType key_press, void* key_press_target, DarkcoreEngine* world, DarkcoreSprite* sprite);
void darkcore_sprite_fire_render (DarkcoreSprite* self, DarkcoreSpriteDelegateType render, void* render_target, DarkcoreEngine* world, DarkcoreSprite* sprite);
void darkcore_sprite_render (DarkcoreSprite* self);
GType darkcore_texture_get_type (void) G_GNUC_CONST;
gint darkcore_sprite_get_texture_index (DarkcoreSprite* self);
DarkcoreTexture* darkcore_engine_getTexture (DarkcoreEngine* self, gint index);
gdouble darkcore_sprite_get_width (DarkcoreSprite* self);
gdouble darkcore_sprite_get_height (DarkcoreSprite* self);
gdouble darkcore_sprite_get_x (DarkcoreSprite* self);
gdouble darkcore_sprite_get_y (DarkcoreSprite* self);
gdouble darkcore_sprite_get_rotation (DarkcoreSprite* self);
guchar darkcore_sprite_get_color_r (DarkcoreSprite* self);
guchar darkcore_sprite_get_color_g (DarkcoreSprite* self);
guchar darkcore_sprite_get_color_b (DarkcoreSprite* self);
void darkcore_sprite_set_x (DarkcoreSprite* self, gdouble value);
void darkcore_sprite_set_y (DarkcoreSprite* self, gdouble value);
void darkcore_sprite_set_rotation (DarkcoreSprite* self, gdouble value);
void darkcore_sprite_set_width (DarkcoreSprite* self, gdouble value);
void darkcore_sprite_set_height (DarkcoreSprite* self, gdouble value);
void darkcore_sprite_set_color_r (DarkcoreSprite* self, guchar value);
void darkcore_sprite_set_color_g (DarkcoreSprite* self, guchar value);
void darkcore_sprite_set_color_b (DarkcoreSprite* self, guchar value);
static void darkcore_sprite_finalize (GObject* obj);
static void _vala_darkcore_sprite_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_darkcore_sprite_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


DarkcoreSprite* darkcore_sprite_construct (GType object_type) {
	DarkcoreSprite * self = NULL;
	self = (DarkcoreSprite*) g_object_new (object_type, NULL);
	return self;
}


DarkcoreSprite* darkcore_sprite_new (void) {
	return darkcore_sprite_construct (DARKCORE_TYPE_SPRITE);
}


DarkcoreSprite* darkcore_sprite_construct_from_file (GType object_type, DarkcoreEngine* world, const gchar* filename) {
	DarkcoreSprite * self = NULL;
	gint _tmp0_;
	g_return_val_if_fail (world != NULL, NULL);
	g_return_val_if_fail (filename != NULL, NULL);
	self = (DarkcoreSprite*) g_object_new (object_type, NULL);
	self->world = world;
	_tmp0_ = darkcore_engine_addTexture (self->world, filename);
	darkcore_sprite_set_texture_index (self, _tmp0_);
	return self;
}


DarkcoreSprite* darkcore_sprite_new_from_file (DarkcoreEngine* world, const gchar* filename) {
	return darkcore_sprite_construct_from_file (DARKCORE_TYPE_SPRITE, world, filename);
}


DarkcoreSprite* darkcore_sprite_construct_from_texture (GType object_type, DarkcoreEngine* world, gint texture_index) {
	DarkcoreSprite * self = NULL;
	g_return_val_if_fail (world != NULL, NULL);
	self = (DarkcoreSprite*) g_object_new (object_type, NULL);
	self->world = world;
	darkcore_sprite_set_texture_index (self, texture_index);
	return self;
}


DarkcoreSprite* darkcore_sprite_new_from_texture (DarkcoreEngine* world, gint texture_index) {
	return darkcore_sprite_construct_from_texture (DARKCORE_TYPE_SPRITE, world, texture_index);
}


void darkcore_sprite_fire_key_press (DarkcoreSprite* self, DarkcoreSpriteDelegateType key_press, void* key_press_target, DarkcoreEngine* world, DarkcoreSprite* sprite) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (world != NULL);
	g_return_if_fail (sprite != NULL);
	key_press (world, sprite, key_press_target);
}


void darkcore_sprite_fire_render (DarkcoreSprite* self, DarkcoreSpriteDelegateType render, void* render_target, DarkcoreEngine* world, DarkcoreSprite* sprite) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (world != NULL);
	g_return_if_fail (sprite != NULL);
	render (world, sprite, render_target);
}


void darkcore_sprite_render (DarkcoreSprite* self) {
	DarkcoreTexture* texture;
	gboolean _tmp1_ = FALSE;
	gdouble half_width;
	gdouble half_height;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (self != NULL);
	texture = NULL;
	if (self->priv->_texture_index > (-1)) {
		DarkcoreTexture* _tmp0_ = NULL;
		glEnable (GL_TEXTURE_2D);
		_tmp0_ = darkcore_engine_getTexture (self->world, self->priv->_texture_index);
		_g_object_unref0 (texture);
		texture = _tmp0_;
	}
	if (texture != NULL) {
		_tmp1_ = texture->loaded > 0;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		glBindTexture (GL_TEXTURE_2D, (GLuint) (texture->texture_id + 1));
		glDepthFunc (GL_LEQUAL);
		glEnable (GL_DEPTH_TEST);
		glBlendFunc (GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
		glEnable (GL_BLEND);
	}
	half_width = self->priv->_width / 2;
	half_height = self->priv->_height / 2;
	glPushMatrix ();
	glTranslated ((GLdouble) self->priv->_x, (GLdouble) self->priv->_y, (GLdouble) 0.00);
	if (self->priv->_rotation != 0.00) {
		glRotated ((GLdouble) self->priv->_rotation, (GLdouble) 0.00, (GLdouble) 0.00, (GLdouble) 1.00);
	}
	glColor3ub ((GLubyte) self->priv->_color_r, (GLubyte) self->priv->_color_g, (GLubyte) self->priv->_color_b);
	glBegin (GL_QUADS);
	glTexCoord2f ((GLfloat) 0.00, (GLfloat) 0.00);
	glVertex3d ((GLdouble) (-half_width), (GLdouble) half_height, (GLdouble) 1);
	glTexCoord2f ((GLfloat) 1.00, (GLfloat) 0.00);
	glVertex3d ((GLdouble) (-half_width), (GLdouble) (-half_height), (GLdouble) 1);
	glTexCoord2f ((GLfloat) 1.00, (GLfloat) 1.00);
	glVertex3d ((GLdouble) half_width, (GLdouble) (-half_height), (GLdouble) 1);
	glTexCoord2f ((GLfloat) 0.00, (GLfloat) 1.00);
	glVertex3d ((GLdouble) half_width, (GLdouble) half_height, (GLdouble) 1);
	glEnd ();
	glPopMatrix ();
	if (texture != NULL) {
		_tmp2_ = texture->loaded > 0;
	} else {
		_tmp2_ = FALSE;
	}
	if (_tmp2_) {
		glDisable (GL_BLEND);
		glDisable (GL_DEPTH_TEST);
		glBindTexture (GL_TEXTURE_2D, (GLuint) 0);
	}
	glDisable (GL_TEXTURE_2D);
	_g_object_unref0 (texture);
}


gdouble darkcore_sprite_get_x (DarkcoreSprite* self) {
	gdouble result;
	g_return_val_if_fail (self != NULL, 0.0);
	result = self->priv->_x;
	return result;
}


void darkcore_sprite_set_x (DarkcoreSprite* self, gdouble value) {
	g_return_if_fail (self != NULL);
	self->priv->_x = value;
	g_object_notify ((GObject *) self, "x");
}


gdouble darkcore_sprite_get_y (DarkcoreSprite* self) {
	gdouble result;
	g_return_val_if_fail (self != NULL, 0.0);
	result = self->priv->_y;
	return result;
}


void darkcore_sprite_set_y (DarkcoreSprite* self, gdouble value) {
	g_return_if_fail (self != NULL);
	self->priv->_y = value;
	g_object_notify ((GObject *) self, "y");
}


gdouble darkcore_sprite_get_rotation (DarkcoreSprite* self) {
	gdouble result;
	g_return_val_if_fail (self != NULL, 0.0);
	result = self->priv->_rotation;
	return result;
}


void darkcore_sprite_set_rotation (DarkcoreSprite* self, gdouble value) {
	g_return_if_fail (self != NULL);
	self->priv->_rotation = value;
	g_object_notify ((GObject *) self, "rotation");
}


gdouble darkcore_sprite_get_width (DarkcoreSprite* self) {
	gdouble result;
	g_return_val_if_fail (self != NULL, 0.0);
	result = self->priv->_width;
	return result;
}


void darkcore_sprite_set_width (DarkcoreSprite* self, gdouble value) {
	g_return_if_fail (self != NULL);
	self->priv->_width = value;
	g_object_notify ((GObject *) self, "width");
}


gdouble darkcore_sprite_get_height (DarkcoreSprite* self) {
	gdouble result;
	g_return_val_if_fail (self != NULL, 0.0);
	result = self->priv->_height;
	return result;
}


void darkcore_sprite_set_height (DarkcoreSprite* self, gdouble value) {
	g_return_if_fail (self != NULL);
	self->priv->_height = value;
	g_object_notify ((GObject *) self, "height");
}


guchar darkcore_sprite_get_color_r (DarkcoreSprite* self) {
	guchar result;
	g_return_val_if_fail (self != NULL, '\0');
	result = self->priv->_color_r;
	return result;
}


void darkcore_sprite_set_color_r (DarkcoreSprite* self, guchar value) {
	g_return_if_fail (self != NULL);
	self->priv->_color_r = value;
	g_object_notify ((GObject *) self, "color-r");
}


guchar darkcore_sprite_get_color_g (DarkcoreSprite* self) {
	guchar result;
	g_return_val_if_fail (self != NULL, '\0');
	result = self->priv->_color_g;
	return result;
}


void darkcore_sprite_set_color_g (DarkcoreSprite* self, guchar value) {
	g_return_if_fail (self != NULL);
	self->priv->_color_g = value;
	g_object_notify ((GObject *) self, "color-g");
}


guchar darkcore_sprite_get_color_b (DarkcoreSprite* self) {
	guchar result;
	g_return_val_if_fail (self != NULL, '\0');
	result = self->priv->_color_b;
	return result;
}


void darkcore_sprite_set_color_b (DarkcoreSprite* self, guchar value) {
	g_return_if_fail (self != NULL);
	self->priv->_color_b = value;
	g_object_notify ((GObject *) self, "color-b");
}


gint darkcore_sprite_get_texture_index (DarkcoreSprite* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_texture_index;
	return result;
}


void darkcore_sprite_set_texture_index (DarkcoreSprite* self, gint value) {
	g_return_if_fail (self != NULL);
	self->priv->_texture_index = value;
	g_object_notify ((GObject *) self, "texture-index");
}


static void darkcore_sprite_class_init (DarkcoreSpriteClass * klass) {
	darkcore_sprite_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (DarkcoreSpritePrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_darkcore_sprite_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_darkcore_sprite_set_property;
	G_OBJECT_CLASS (klass)->finalize = darkcore_sprite_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_SPRITE_X, g_param_spec_double ("x", "x", "x", -G_MAXDOUBLE, G_MAXDOUBLE, 0.00, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_SPRITE_Y, g_param_spec_double ("y", "y", "y", -G_MAXDOUBLE, G_MAXDOUBLE, 0.00, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_SPRITE_ROTATION, g_param_spec_double ("rotation", "rotation", "rotation", -G_MAXDOUBLE, G_MAXDOUBLE, 0.00, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_SPRITE_WIDTH, g_param_spec_double ("width", "width", "width", -G_MAXDOUBLE, G_MAXDOUBLE, 32.00, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_SPRITE_HEIGHT, g_param_spec_double ("height", "height", "height", -G_MAXDOUBLE, G_MAXDOUBLE, 32.00, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_SPRITE_COLOR_R, g_param_spec_uchar ("color-r", "color-r", "color-r", 0, G_MAXUINT8, (guchar) 255, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_SPRITE_COLOR_G, g_param_spec_uchar ("color-g", "color-g", "color-g", 0, G_MAXUINT8, (guchar) 255, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_SPRITE_COLOR_B, g_param_spec_uchar ("color-b", "color-b", "color-b", 0, G_MAXUINT8, (guchar) 255, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DARKCORE_SPRITE_TEXTURE_INDEX, g_param_spec_int ("texture-index", "texture-index", "texture-index", G_MININT, G_MAXINT, -1, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void darkcore_sprite_instance_init (DarkcoreSprite * self) {
	self->priv = DARKCORE_SPRITE_GET_PRIVATE (self);
	self->priv->_x = 0.00;
	self->priv->_y = 0.00;
	self->priv->_rotation = 0.00;
	self->priv->_width = 32.00;
	self->priv->_height = 32.00;
	self->priv->_color_r = (guchar) 255;
	self->priv->_color_g = (guchar) 255;
	self->priv->_color_b = (guchar) 255;
	self->priv->_texture_index = -1;
}


static void darkcore_sprite_finalize (GObject* obj) {
	DarkcoreSprite * self;
	self = DARKCORE_SPRITE (obj);
	(self->on_key_press_target_destroy_notify == NULL) ? NULL : (self->on_key_press_target_destroy_notify (self->on_key_press_target), NULL);
	self->on_key_press = NULL;
	self->on_key_press_target = NULL;
	self->on_key_press_target_destroy_notify = NULL;
	(self->on_render_target_destroy_notify == NULL) ? NULL : (self->on_render_target_destroy_notify (self->on_render_target), NULL);
	self->on_render = NULL;
	self->on_render_target = NULL;
	self->on_render_target_destroy_notify = NULL;
	G_OBJECT_CLASS (darkcore_sprite_parent_class)->finalize (obj);
}


GType darkcore_sprite_get_type (void) {
	static volatile gsize darkcore_sprite_type_id__volatile = 0;
	if (g_once_init_enter (&darkcore_sprite_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DarkcoreSpriteClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) darkcore_sprite_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DarkcoreSprite), 0, (GInstanceInitFunc) darkcore_sprite_instance_init, NULL };
		GType darkcore_sprite_type_id;
		darkcore_sprite_type_id = g_type_register_static (G_TYPE_OBJECT, "DarkcoreSprite", &g_define_type_info, 0);
		g_once_init_leave (&darkcore_sprite_type_id__volatile, darkcore_sprite_type_id);
	}
	return darkcore_sprite_type_id__volatile;
}


static void _vala_darkcore_sprite_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	DarkcoreSprite * self;
	self = DARKCORE_SPRITE (object);
	switch (property_id) {
		case DARKCORE_SPRITE_X:
		g_value_set_double (value, darkcore_sprite_get_x (self));
		break;
		case DARKCORE_SPRITE_Y:
		g_value_set_double (value, darkcore_sprite_get_y (self));
		break;
		case DARKCORE_SPRITE_ROTATION:
		g_value_set_double (value, darkcore_sprite_get_rotation (self));
		break;
		case DARKCORE_SPRITE_WIDTH:
		g_value_set_double (value, darkcore_sprite_get_width (self));
		break;
		case DARKCORE_SPRITE_HEIGHT:
		g_value_set_double (value, darkcore_sprite_get_height (self));
		break;
		case DARKCORE_SPRITE_COLOR_R:
		g_value_set_uchar (value, darkcore_sprite_get_color_r (self));
		break;
		case DARKCORE_SPRITE_COLOR_G:
		g_value_set_uchar (value, darkcore_sprite_get_color_g (self));
		break;
		case DARKCORE_SPRITE_COLOR_B:
		g_value_set_uchar (value, darkcore_sprite_get_color_b (self));
		break;
		case DARKCORE_SPRITE_TEXTURE_INDEX:
		g_value_set_int (value, darkcore_sprite_get_texture_index (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_darkcore_sprite_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	DarkcoreSprite * self;
	self = DARKCORE_SPRITE (object);
	switch (property_id) {
		case DARKCORE_SPRITE_X:
		darkcore_sprite_set_x (self, g_value_get_double (value));
		break;
		case DARKCORE_SPRITE_Y:
		darkcore_sprite_set_y (self, g_value_get_double (value));
		break;
		case DARKCORE_SPRITE_ROTATION:
		darkcore_sprite_set_rotation (self, g_value_get_double (value));
		break;
		case DARKCORE_SPRITE_WIDTH:
		darkcore_sprite_set_width (self, g_value_get_double (value));
		break;
		case DARKCORE_SPRITE_HEIGHT:
		darkcore_sprite_set_height (self, g_value_get_double (value));
		break;
		case DARKCORE_SPRITE_COLOR_R:
		darkcore_sprite_set_color_r (self, g_value_get_uchar (value));
		break;
		case DARKCORE_SPRITE_COLOR_G:
		darkcore_sprite_set_color_g (self, g_value_get_uchar (value));
		break;
		case DARKCORE_SPRITE_COLOR_B:
		darkcore_sprite_set_color_b (self, g_value_get_uchar (value));
		break;
		case DARKCORE_SPRITE_TEXTURE_INDEX:
		darkcore_sprite_set_texture_index (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



