/* ball.c generated by valac 0.12.0, the Vala compiler
 * generated from ball.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <GL/gl.h>
#include <SDL.h>
#include <gsl/gsl_vector_double.h>


#define DARKCORE_TYPE_SPRITE (darkcore_sprite_get_type ())
#define DARKCORE_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_SPRITE, DarkcoreSprite))
#define DARKCORE_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_SPRITE, DarkcoreSpriteClass))
#define DARKCORE_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_SPRITE))
#define DARKCORE_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_SPRITE))
#define DARKCORE_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_SPRITE, DarkcoreSpriteClass))

typedef struct _DarkcoreSprite DarkcoreSprite;
typedef struct _DarkcoreSpriteClass DarkcoreSpriteClass;
typedef struct _DarkcoreSpritePrivate DarkcoreSpritePrivate;

#define DARKCORE_TYPE_ENGINE (darkcore_engine_get_type ())
#define DARKCORE_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_ENGINE, DarkcoreEngine))
#define DARKCORE_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_ENGINE, DarkcoreEngineClass))
#define DARKCORE_IS_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_ENGINE))
#define DARKCORE_IS_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_ENGINE))
#define DARKCORE_ENGINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_ENGINE, DarkcoreEngineClass))

typedef struct _DarkcoreEngine DarkcoreEngine;
typedef struct _DarkcoreEngineClass DarkcoreEngineClass;

#define TYPE_BALL (ball_get_type ())
#define BALL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BALL, Ball))
#define BALL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BALL, BallClass))
#define IS_BALL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BALL))
#define IS_BALL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BALL))
#define BALL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BALL, BallClass))

typedef struct _Ball Ball;
typedef struct _BallClass BallClass;
typedef struct _BallPrivate BallPrivate;
typedef struct _DarkcoreEnginePrivate DarkcoreEnginePrivate;

#define DARKCORE_TYPE_TEXTURE (darkcore_texture_get_type ())
#define DARKCORE_TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_TEXTURE, DarkcoreTexture))
#define DARKCORE_TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_TEXTURE, DarkcoreTextureClass))
#define DARKCORE_IS_TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_TEXTURE))
#define DARKCORE_IS_TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_TEXTURE))
#define DARKCORE_TEXTURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_TEXTURE, DarkcoreTextureClass))

typedef struct _DarkcoreTexture DarkcoreTexture;
typedef struct _DarkcoreTextureClass DarkcoreTextureClass;

#define DARKCORE_TYPE_KEY_STATE (darkcore_key_state_get_type ())
#define DARKCORE_KEY_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_KEY_STATE, DarkcoreKeyState))
#define DARKCORE_KEY_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_KEY_STATE, DarkcoreKeyStateClass))
#define DARKCORE_IS_KEY_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_KEY_STATE))
#define DARKCORE_IS_KEY_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_KEY_STATE))
#define DARKCORE_KEY_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_KEY_STATE, DarkcoreKeyStateClass))

typedef struct _DarkcoreKeyState DarkcoreKeyState;
typedef struct _DarkcoreKeyStateClass DarkcoreKeyStateClass;
typedef gsl_vector DarkcoreVector;
#define _gsl_vector_free0(var) ((var == NULL) ? NULL : (var = (gsl_vector_free (var), NULL)))

typedef void (*DarkcoreSpriteDelegateType) (DarkcoreEngine* world, DarkcoreSprite* sprite, void* user_data);
struct _DarkcoreSprite {
	GObject parent_instance;
	DarkcoreSpritePrivate * priv;
	DarkcoreSpriteDelegateType on_key_press;
	gpointer on_key_press_target;
	GDestroyNotify on_key_press_target_destroy_notify;
	DarkcoreSpriteDelegateType on_render;
	gpointer on_render_target;
	GDestroyNotify on_render_target_destroy_notify;
	DarkcoreEngine* world;
};

struct _DarkcoreSpriteClass {
	GObjectClass parent_class;
};

struct _Ball {
	DarkcoreSprite parent_instance;
	BallPrivate * priv;
	gdouble velocity_x;
	gdouble velocity_y;
};

struct _BallClass {
	DarkcoreSpriteClass parent_class;
};

struct _BallPrivate {
	gdouble _acceleration;
	DarkcoreSprite* _left_paddle;
	DarkcoreSprite* _right_paddle;
};

typedef void (*DarkcoreEngineDelegateType) (DarkcoreEngine* world, void* user_data);
struct _DarkcoreEngine {
	GObject parent_instance;
	DarkcoreEnginePrivate * priv;
	DarkcoreEngineDelegateType on_loop_events_00;
	gpointer on_loop_events_00_target;
	GDestroyNotify on_loop_events_00_target_destroy_notify;
	DarkcoreEngineDelegateType on_loop_events_01;
	gpointer on_loop_events_01_target;
	GDestroyNotify on_loop_events_01_target_destroy_notify;
	DarkcoreEngineDelegateType on_loop_events_02;
	gpointer on_loop_events_02_target;
	GDestroyNotify on_loop_events_02_target_destroy_notify;
	DarkcoreEngineDelegateType on_loop_events_03;
	gpointer on_loop_events_03_target;
	GDestroyNotify on_loop_events_03_target_destroy_notify;
	DarkcoreEngineDelegateType on_loop_events_04;
	gpointer on_loop_events_04_target;
	GDestroyNotify on_loop_events_04_target_destroy_notify;
	GeeArrayList* textures;
	GeeArrayList* sprites;
	GLuint tids[32];
	DarkcoreKeyState* keys;
	DarkcoreSprite* player;
	SDL_Surface* screen;
	gboolean done;
	gint width;
	gint height;
};

struct _DarkcoreEngineClass {
	GObjectClass parent_class;
};


static gpointer ball_parent_class = NULL;

GType darkcore_sprite_get_type (void) G_GNUC_CONST;
GType darkcore_engine_get_type (void) G_GNUC_CONST;
GType ball_get_type (void) G_GNUC_CONST;
#define BALL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_BALL, BallPrivate))
enum  {
	BALL_DUMMY_PROPERTY,
	BALL_ACCELERATION,
	BALL_LEFT_PADDLE,
	BALL_RIGHT_PADDLE
};
Ball* ball_new (DarkcoreEngine** engine);
Ball* ball_construct (GType object_type, DarkcoreEngine** engine);
void ball_set_left_paddle (Ball* self, DarkcoreSprite* value);
void ball_set_right_paddle (Ball* self, DarkcoreSprite* value);
DarkcoreSprite* darkcore_sprite_new_from_file (DarkcoreEngine* world, const gchar* filename);
DarkcoreSprite* darkcore_sprite_construct_from_file (GType object_type, DarkcoreEngine* world, const gchar* filename);
void darkcore_sprite_set_width (DarkcoreSprite* self, gdouble value);
void darkcore_sprite_set_height (DarkcoreSprite* self, gdouble value);
GType darkcore_texture_get_type (void) G_GNUC_CONST;
GType darkcore_key_state_get_type (void) G_GNUC_CONST;
void darkcore_sprite_set_x (DarkcoreSprite* self, gdouble value);
void darkcore_sprite_set_y (DarkcoreSprite* self, gdouble value);
static void _lambda1_ (DarkcoreEngine* engine, DarkcoreSprite* ball, Ball* self);
gdouble darkcore_sprite_get_height (DarkcoreSprite* self);
gdouble darkcore_sprite_get_width (DarkcoreSprite* self);
gdouble darkcore_sprite_get_y (DarkcoreSprite* self);
gdouble darkcore_sprite_get_x (DarkcoreSprite* self);
DarkcoreSprite* ball_get_left_paddle (Ball* self);
DarkcoreSprite* ball_get_right_paddle (Ball* self);
gboolean ball_has_hit_paddle (Ball* self, DarkcoreSprite* sprite);
gdouble ball_get_acceleration (Ball* self);
gdouble darkcore_sprite_get_rotation (DarkcoreSprite* self);
void darkcore_sprite_set_rotation (DarkcoreSprite* self, gdouble value);
static void __lambda1__darkcore_sprite_delegate_type (DarkcoreEngine* world, DarkcoreSprite* sprite, gpointer self);
DarkcoreVector* darkcore_vector_new (gsize n);
DarkcoreVector* darkcore_vector_new (gsize n);
gboolean darkcore_collision_circle_in_rectangle (DarkcoreVector* v1, DarkcoreVector* v2, DarkcoreVector* position, gdouble radius);
void ball_set_acceleration (Ball* self, gdouble value);
static void ball_finalize (GObject* obj);
static void _vala_ball_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_ball_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static void _lambda1_ (DarkcoreEngine* engine, DarkcoreSprite* ball, Ball* self) {
	gdouble _tmp0_;
	gdouble half_height;
	gdouble _tmp1_;
	gdouble half_width;
	gdouble _tmp2_;
	gdouble _tmp4_;
	gdouble _tmp6_;
	gdouble _tmp8_;
	gdouble _tmp18_;
	gdouble _tmp19_;
	gdouble _tmp20_;
	g_return_if_fail (engine != NULL);
	g_return_if_fail (ball != NULL);
	_tmp0_ = darkcore_sprite_get_height ((DarkcoreSprite*) self);
	half_height = _tmp0_ / 2.00;
	_tmp1_ = darkcore_sprite_get_width ((DarkcoreSprite*) self);
	half_width = _tmp1_ / 2.00;
	_tmp2_ = darkcore_sprite_get_y ((DarkcoreSprite*) self);
	if (((_tmp2_ + half_height) + self->velocity_y) >= engine->height) {
		gdouble _tmp3_;
		_tmp3_ = fabs (self->velocity_y);
		self->velocity_y = -_tmp3_;
	}
	_tmp4_ = darkcore_sprite_get_y ((DarkcoreSprite*) self);
	if (((_tmp4_ - half_height) - self->velocity_y) <= 0) {
		gdouble _tmp5_;
		_tmp5_ = fabs (self->velocity_y);
		self->velocity_y = _tmp5_;
	}
	_tmp6_ = darkcore_sprite_get_x ((DarkcoreSprite*) self);
	if (((_tmp6_ + half_width) + self->velocity_x) >= engine->width) {
		gdouble _tmp7_;
		_tmp7_ = fabs (self->velocity_x);
		self->velocity_x = -_tmp7_;
	}
	_tmp8_ = darkcore_sprite_get_x ((DarkcoreSprite*) self);
	if (((_tmp8_ - half_width) - self->velocity_x) <= 0) {
		gdouble _tmp9_;
		_tmp9_ = fabs (self->velocity_x);
		self->velocity_x = _tmp9_;
	}
	{
		gint i;
		i = 0;
		{
			gboolean _tmp10_;
			_tmp10_ = TRUE;
			while (TRUE) {
				DarkcoreSprite* paddle;
				gboolean _tmp11_ = FALSE;
				gboolean _tmp13_ = FALSE;
				if (!_tmp10_) {
					i++;
				}
				_tmp10_ = FALSE;
				if (!(i < 2)) {
					break;
				}
				paddle = NULL;
				if (i == 0) {
					_tmp11_ = self->priv->_left_paddle != NULL;
				} else {
					_tmp11_ = FALSE;
				}
				if (_tmp11_) {
					paddle = self->priv->_left_paddle;
				} else {
					gboolean _tmp12_ = FALSE;
					if (i == 1) {
						_tmp12_ = self->priv->_right_paddle != NULL;
					} else {
						_tmp12_ = FALSE;
					}
					if (_tmp12_) {
						paddle = self->priv->_right_paddle;
					}
				}
				if (paddle != NULL) {
					gboolean _tmp14_;
					_tmp14_ = ball_has_hit_paddle (self, paddle);
					_tmp13_ = _tmp14_;
				} else {
					_tmp13_ = FALSE;
				}
				if (_tmp13_) {
					gdouble _tmp15_;
					gdouble _tmp16_;
					gdouble _tmp17_;
					_tmp15_ = fabs (self->velocity_x);
					self->velocity_x = _tmp15_ + self->priv->_acceleration;
					if (paddle == self->priv->_right_paddle) {
						self->velocity_x = self->velocity_x * ((gdouble) (-1));
					}
					_tmp16_ = darkcore_sprite_get_y (paddle);
					_tmp17_ = darkcore_sprite_get_y ((DarkcoreSprite*) self);
					self->velocity_y = -((_tmp16_ - _tmp17_) / half_height);
				}
			}
		}
	}
	_tmp18_ = darkcore_sprite_get_x ((DarkcoreSprite*) self);
	darkcore_sprite_set_x ((DarkcoreSprite*) self, _tmp18_ + self->velocity_x);
	_tmp19_ = darkcore_sprite_get_y ((DarkcoreSprite*) self);
	darkcore_sprite_set_y ((DarkcoreSprite*) self, _tmp19_ + self->velocity_y);
	_tmp20_ = darkcore_sprite_get_rotation ((DarkcoreSprite*) self);
	darkcore_sprite_set_rotation ((DarkcoreSprite*) self, _tmp20_ + 1.0);
}


static void __lambda1__darkcore_sprite_delegate_type (DarkcoreEngine* world, DarkcoreSprite* sprite, gpointer self) {
	_lambda1_ (world, sprite, self);
}


Ball* ball_construct (GType object_type, DarkcoreEngine** engine) {
	Ball * self = NULL;
	g_return_val_if_fail (engine != NULL, NULL);
	ball_set_left_paddle (self, NULL);
	ball_set_right_paddle (self, NULL);
	self = (Ball*) darkcore_sprite_construct_from_file (object_type, *engine, "resources/ball.png");
	darkcore_sprite_set_width ((DarkcoreSprite*) self, 64.00);
	darkcore_sprite_set_height ((DarkcoreSprite*) self, 64.00);
	darkcore_sprite_set_x ((DarkcoreSprite*) self, (gdouble) ((*engine)->width / 2));
	darkcore_sprite_set_y ((DarkcoreSprite*) self, (gdouble) ((*engine)->height / 2));
	self->velocity_x = 4.00;
	self->velocity_y = 4.00;
	(((DarkcoreSprite*) self)->on_render_target_destroy_notify == NULL) ? NULL : (((DarkcoreSprite*) self)->on_render_target_destroy_notify (((DarkcoreSprite*) self)->on_render_target), NULL);
	((DarkcoreSprite*) self)->on_render = NULL;
	((DarkcoreSprite*) self)->on_render_target = NULL;
	((DarkcoreSprite*) self)->on_render_target_destroy_notify = NULL;
	((DarkcoreSprite*) self)->on_render = __lambda1__darkcore_sprite_delegate_type;
	((DarkcoreSprite*) self)->on_render_target = g_object_ref (self);
	((DarkcoreSprite*) self)->on_render_target_destroy_notify = g_object_unref;
	return self;
}


Ball* ball_new (DarkcoreEngine** engine) {
	return ball_construct (TYPE_BALL, engine);
}


gboolean ball_has_hit_paddle (Ball* self, DarkcoreSprite* sprite) {
	gboolean result = FALSE;
	DarkcoreVector* _tmp0_ = NULL;
	DarkcoreVector* circle_vector;
	gdouble _tmp1_;
	gdouble _tmp2_;
	DarkcoreVector* _tmp3_ = NULL;
	DarkcoreVector* min_vector;
	DarkcoreVector* _tmp4_ = NULL;
	DarkcoreVector* max_vector;
	gdouble _tmp5_;
	gdouble _tmp6_;
	gdouble _tmp7_;
	gdouble _tmp8_;
	gdouble _tmp9_;
	gdouble _tmp10_;
	gdouble _tmp11_;
	gdouble _tmp12_;
	gdouble _tmp13_;
	gboolean _tmp14_;
	gboolean hit;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (sprite != NULL, FALSE);
	_tmp0_ = darkcore_vector_new ((gsize) 2);
	circle_vector = _tmp0_;
	_tmp1_ = darkcore_sprite_get_x ((DarkcoreSprite*) self);
	gsl_vector_set ((gsl_vector*) circle_vector, (gsize) 0, _tmp1_);
	_tmp2_ = darkcore_sprite_get_y ((DarkcoreSprite*) self);
	gsl_vector_set ((gsl_vector*) circle_vector, (gsize) 1, _tmp2_);
	_tmp3_ = darkcore_vector_new ((gsize) 2);
	min_vector = _tmp3_;
	_tmp4_ = darkcore_vector_new ((gsize) 2);
	max_vector = _tmp4_;
	_tmp5_ = darkcore_sprite_get_x (sprite);
	_tmp6_ = darkcore_sprite_get_width (sprite);
	gsl_vector_set ((gsl_vector*) min_vector, (gsize) 0, _tmp5_ - (_tmp6_ / 2));
	_tmp7_ = darkcore_sprite_get_y (sprite);
	_tmp8_ = darkcore_sprite_get_height (sprite);
	gsl_vector_set ((gsl_vector*) min_vector, (gsize) 1, _tmp7_ - (_tmp8_ / 2));
	_tmp9_ = darkcore_sprite_get_x (sprite);
	_tmp10_ = darkcore_sprite_get_width (sprite);
	gsl_vector_set ((gsl_vector*) max_vector, (gsize) 0, _tmp9_ + (_tmp10_ / 2));
	_tmp11_ = darkcore_sprite_get_y (sprite);
	_tmp12_ = darkcore_sprite_get_height (sprite);
	gsl_vector_set ((gsl_vector*) max_vector, (gsize) 1, _tmp11_ + (_tmp12_ / 2));
	_tmp13_ = darkcore_sprite_get_width ((DarkcoreSprite*) self);
	_tmp14_ = darkcore_collision_circle_in_rectangle (min_vector, max_vector, circle_vector, _tmp13_ / 2.00);
	hit = _tmp14_;
	result = hit;
	_gsl_vector_free0 (max_vector);
	_gsl_vector_free0 (min_vector);
	_gsl_vector_free0 (circle_vector);
	return result;
}


gdouble ball_get_acceleration (Ball* self) {
	gdouble result;
	g_return_val_if_fail (self != NULL, 0.0);
	result = self->priv->_acceleration;
	return result;
}


void ball_set_acceleration (Ball* self, gdouble value) {
	g_return_if_fail (self != NULL);
	self->priv->_acceleration = value;
	g_object_notify ((GObject *) self, "acceleration");
}


DarkcoreSprite* ball_get_left_paddle (Ball* self) {
	DarkcoreSprite* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_left_paddle;
	return result;
}


void ball_set_left_paddle (Ball* self, DarkcoreSprite* value) {
	g_return_if_fail (self != NULL);
	self->priv->_left_paddle = value;
	g_object_notify ((GObject *) self, "left-paddle");
}


DarkcoreSprite* ball_get_right_paddle (Ball* self) {
	DarkcoreSprite* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_right_paddle;
	return result;
}


void ball_set_right_paddle (Ball* self, DarkcoreSprite* value) {
	g_return_if_fail (self != NULL);
	self->priv->_right_paddle = value;
	g_object_notify ((GObject *) self, "right-paddle");
}


static void ball_class_init (BallClass * klass) {
	ball_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (BallPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_ball_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_ball_set_property;
	G_OBJECT_CLASS (klass)->finalize = ball_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), BALL_ACCELERATION, g_param_spec_double ("acceleration", "acceleration", "acceleration", -G_MAXDOUBLE, G_MAXDOUBLE, 0.100, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), BALL_LEFT_PADDLE, g_param_spec_object ("left-paddle", "left-paddle", "left-paddle", DARKCORE_TYPE_SPRITE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), BALL_RIGHT_PADDLE, g_param_spec_object ("right-paddle", "right-paddle", "right-paddle", DARKCORE_TYPE_SPRITE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void ball_instance_init (Ball * self) {
	self->priv = BALL_GET_PRIVATE (self);
	self->priv->_acceleration = 0.100;
	self->priv->_left_paddle = NULL;
	self->priv->_right_paddle = NULL;
}


static void ball_finalize (GObject* obj) {
	Ball * self;
	self = BALL (obj);
	G_OBJECT_CLASS (ball_parent_class)->finalize (obj);
}


GType ball_get_type (void) {
	static volatile gsize ball_type_id__volatile = 0;
	if (g_once_init_enter (&ball_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BallClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ball_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Ball), 0, (GInstanceInitFunc) ball_instance_init, NULL };
		GType ball_type_id;
		ball_type_id = g_type_register_static (DARKCORE_TYPE_SPRITE, "Ball", &g_define_type_info, 0);
		g_once_init_leave (&ball_type_id__volatile, ball_type_id);
	}
	return ball_type_id__volatile;
}


static void _vala_ball_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	Ball * self;
	self = BALL (object);
	switch (property_id) {
		case BALL_ACCELERATION:
		g_value_set_double (value, ball_get_acceleration (self));
		break;
		case BALL_LEFT_PADDLE:
		g_value_set_object (value, ball_get_left_paddle (self));
		break;
		case BALL_RIGHT_PADDLE:
		g_value_set_object (value, ball_get_right_paddle (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_ball_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	Ball * self;
	self = BALL (object);
	switch (property_id) {
		case BALL_ACCELERATION:
		ball_set_acceleration (self, g_value_get_double (value));
		break;
		case BALL_LEFT_PADDLE:
		ball_set_left_paddle (self, g_value_get_object (value));
		break;
		case BALL_RIGHT_PADDLE:
		ball_set_right_paddle (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



