/* darkcore.c generated by valac 0.12.0, the Vala compiler
 * generated from darkcore.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <GL/gl.h>



extern GLuint darkcore_texture_inc;
GLuint darkcore_texture_inc = (GLuint) 0;




