/* main.c generated by valac 0.12.0, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gee.h>
#include <GL/gl.h>
#include <SDL.h>


#define TYPE_GAME_DEMO (game_demo_get_type ())
#define GAME_DEMO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME_DEMO, GameDemo))
#define GAME_DEMO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME_DEMO, GameDemoClass))
#define IS_GAME_DEMO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME_DEMO))
#define IS_GAME_DEMO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME_DEMO))
#define GAME_DEMO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME_DEMO, GameDemoClass))

typedef struct _GameDemo GameDemo;
typedef struct _GameDemoClass GameDemoClass;
typedef struct _GameDemoPrivate GameDemoPrivate;

#define DARKCORE_TYPE_ENGINE (darkcore_engine_get_type ())
#define DARKCORE_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_ENGINE, DarkcoreEngine))
#define DARKCORE_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_ENGINE, DarkcoreEngineClass))
#define DARKCORE_IS_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_ENGINE))
#define DARKCORE_IS_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_ENGINE))
#define DARKCORE_ENGINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_ENGINE, DarkcoreEngineClass))

typedef struct _DarkcoreEngine DarkcoreEngine;
typedef struct _DarkcoreEngineClass DarkcoreEngineClass;

#define DARKCORE_TYPE_SPRITE (darkcore_sprite_get_type ())
#define DARKCORE_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_SPRITE, DarkcoreSprite))
#define DARKCORE_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_SPRITE, DarkcoreSpriteClass))
#define DARKCORE_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_SPRITE))
#define DARKCORE_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_SPRITE))
#define DARKCORE_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_SPRITE, DarkcoreSpriteClass))

typedef struct _DarkcoreSprite DarkcoreSprite;
typedef struct _DarkcoreSpriteClass DarkcoreSpriteClass;
typedef struct _DarkcoreSpritePrivate DarkcoreSpritePrivate;
typedef struct _DarkcoreEnginePrivate DarkcoreEnginePrivate;

#define DARKCORE_TYPE_TEXTURE (darkcore_texture_get_type ())
#define DARKCORE_TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_TEXTURE, DarkcoreTexture))
#define DARKCORE_TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_TEXTURE, DarkcoreTextureClass))
#define DARKCORE_IS_TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_TEXTURE))
#define DARKCORE_IS_TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_TEXTURE))
#define DARKCORE_TEXTURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_TEXTURE, DarkcoreTextureClass))

typedef struct _DarkcoreTexture DarkcoreTexture;
typedef struct _DarkcoreTextureClass DarkcoreTextureClass;

#define DARKCORE_TYPE_KEY_STATE (darkcore_key_state_get_type ())
#define DARKCORE_KEY_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DARKCORE_TYPE_KEY_STATE, DarkcoreKeyState))
#define DARKCORE_KEY_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DARKCORE_TYPE_KEY_STATE, DarkcoreKeyStateClass))
#define DARKCORE_IS_KEY_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DARKCORE_TYPE_KEY_STATE))
#define DARKCORE_IS_KEY_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DARKCORE_TYPE_KEY_STATE))
#define DARKCORE_KEY_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DARKCORE_TYPE_KEY_STATE, DarkcoreKeyStateClass))

typedef struct _DarkcoreKeyState DarkcoreKeyState;
typedef struct _DarkcoreKeyStateClass DarkcoreKeyStateClass;

#define TYPE_BALL (ball_get_type ())
#define BALL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BALL, Ball))
#define BALL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BALL, BallClass))
#define IS_BALL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BALL))
#define IS_BALL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BALL))
#define BALL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BALL, BallClass))

typedef struct _Ball Ball;
typedef struct _BallClass BallClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GameDemo {
	GObject parent_instance;
	GameDemoPrivate * priv;
};

struct _GameDemoClass {
	GObjectClass parent_class;
};

typedef void (*DarkcoreSpriteDelegateType) (DarkcoreEngine* world, DarkcoreSprite* sprite, void* user_data);
struct _DarkcoreSprite {
	GObject parent_instance;
	DarkcoreSpritePrivate * priv;
	DarkcoreSpriteDelegateType on_key_press;
	gpointer on_key_press_target;
	GDestroyNotify on_key_press_target_destroy_notify;
	DarkcoreSpriteDelegateType on_render;
	gpointer on_render_target;
	GDestroyNotify on_render_target_destroy_notify;
	DarkcoreEngine* world;
};

struct _DarkcoreSpriteClass {
	GObjectClass parent_class;
};

typedef void (*DarkcoreEngineDelegateType) (DarkcoreEngine* world, void* user_data);
struct _DarkcoreEngine {
	GObject parent_instance;
	DarkcoreEnginePrivate * priv;
	DarkcoreEngineDelegateType on_loop_events_00;
	gpointer on_loop_events_00_target;
	GDestroyNotify on_loop_events_00_target_destroy_notify;
	DarkcoreEngineDelegateType on_loop_events_01;
	gpointer on_loop_events_01_target;
	GDestroyNotify on_loop_events_01_target_destroy_notify;
	DarkcoreEngineDelegateType on_loop_events_02;
	gpointer on_loop_events_02_target;
	GDestroyNotify on_loop_events_02_target_destroy_notify;
	DarkcoreEngineDelegateType on_loop_events_03;
	gpointer on_loop_events_03_target;
	GDestroyNotify on_loop_events_03_target_destroy_notify;
	DarkcoreEngineDelegateType on_loop_events_04;
	gpointer on_loop_events_04_target;
	GDestroyNotify on_loop_events_04_target_destroy_notify;
	GeeArrayList* textures;
	GeeArrayList* sprites;
	GLuint tids[32];
	DarkcoreKeyState* keys;
	DarkcoreSprite* player;
	SDL_Surface* screen;
	gboolean done;
	gint width;
	gint height;
};

struct _DarkcoreEngineClass {
	GObjectClass parent_class;
};


static gpointer game_demo_parent_class = NULL;

GType game_demo_get_type (void) G_GNUC_CONST;
enum  {
	GAME_DEMO_DUMMY_PROPERTY
};
gint game_demo_main (gchar** args, int args_length1);
DarkcoreEngine* darkcore_engine_new (gint width, gint height);
DarkcoreEngine* darkcore_engine_construct (GType object_type, gint width, gint height);
GType darkcore_engine_get_type (void) G_GNUC_CONST;
DarkcoreSprite* darkcore_sprite_new (void);
DarkcoreSprite* darkcore_sprite_construct (GType object_type);
GType darkcore_sprite_get_type (void) G_GNUC_CONST;
gdouble darkcore_sprite_get_x (DarkcoreSprite* self);
void darkcore_sprite_set_x (DarkcoreSprite* self, gdouble value);
gdouble darkcore_sprite_get_y (DarkcoreSprite* self);
void darkcore_sprite_set_y (DarkcoreSprite* self, gdouble value);
void darkcore_sprite_set_height (DarkcoreSprite* self, gdouble value);
static void _lambda0_ (DarkcoreEngine* engine, DarkcoreSprite* player);
GType darkcore_texture_get_type (void) G_GNUC_CONST;
GType darkcore_key_state_get_type (void) G_GNUC_CONST;
gboolean darkcore_key_state_get_up (DarkcoreKeyState* self);
gboolean darkcore_key_state_get_down (DarkcoreKeyState* self);
gdouble darkcore_sprite_get_width (DarkcoreSprite* self);
gdouble darkcore_sprite_get_height (DarkcoreSprite* self);
static void __lambda0__darkcore_sprite_delegate_type (DarkcoreEngine* world, DarkcoreSprite* sprite, gpointer self);
Ball* ball_new (DarkcoreEngine** engine);
Ball* ball_construct (GType object_type, DarkcoreEngine** engine);
GType ball_get_type (void) G_GNUC_CONST;
void ball_set_left_paddle (Ball* self, DarkcoreSprite* value);
void darkcore_engine_run (DarkcoreEngine* self);
GameDemo* game_demo_new (void);
GameDemo* game_demo_construct (GType object_type);


static void _lambda0_ (DarkcoreEngine* engine, DarkcoreSprite* player) {
	gint x;
	gint y;
	gboolean _tmp0_;
	gboolean _tmp1_;
	gdouble _tmp2_;
	gdouble _tmp3_;
	gdouble _tmp6_;
	gdouble _tmp7_;
	gdouble _tmp10_;
	g_return_if_fail (engine != NULL);
	g_return_if_fail (player != NULL);
	x = 0;
	y = 0;
	_tmp0_ = darkcore_key_state_get_up (engine->keys);
	if (_tmp0_) {
		y = y + 4;
	}
	_tmp1_ = darkcore_key_state_get_down (engine->keys);
	if (_tmp1_) {
		y = y - 4;
	}
	_tmp2_ = darkcore_sprite_get_x (player);
	_tmp3_ = darkcore_sprite_get_width (player);
	if (((_tmp2_ + x) + (_tmp3_ / 2)) >= engine->width) {
		x = 0;
	} else {
		gdouble _tmp4_;
		gdouble _tmp5_;
		_tmp4_ = darkcore_sprite_get_x (player);
		_tmp5_ = darkcore_sprite_get_width (player);
		if (((_tmp4_ + x) - (_tmp5_ / 2)) <= 0) {
			x = 0;
		}
	}
	_tmp6_ = darkcore_sprite_get_y (player);
	_tmp7_ = darkcore_sprite_get_height (player);
	if (((_tmp6_ + y) + (_tmp7_ / 2)) >= engine->height) {
		y = 0;
	} else {
		gdouble _tmp8_;
		gdouble _tmp9_;
		_tmp8_ = darkcore_sprite_get_y (player);
		_tmp9_ = darkcore_sprite_get_height (player);
		if (((_tmp8_ + y) - (_tmp9_ / 2)) <= 0) {
			y = 0;
		}
	}
	_tmp10_ = darkcore_sprite_get_y (player);
	darkcore_sprite_set_y (player, _tmp10_ + ((gdouble) y));
}


static void __lambda0__darkcore_sprite_delegate_type (DarkcoreEngine* world, DarkcoreSprite* sprite, gpointer self) {
	_lambda0_ (world, sprite);
}


gint game_demo_main (gchar** args, int args_length1) {
	gint result = 0;
	DarkcoreEngine* _tmp0_ = NULL;
	DarkcoreEngine* engine;
	DarkcoreSprite* _tmp1_ = NULL;
	DarkcoreSprite* player;
	gdouble _tmp2_;
	gdouble _tmp3_;
	Ball* _tmp4_ = NULL;
	Ball* ball;
	_tmp0_ = darkcore_engine_new (640, 480);
	engine = _tmp0_;
	_tmp1_ = darkcore_sprite_new ();
	player = _tmp1_;
	player->world = engine;
	_tmp2_ = darkcore_sprite_get_x (player);
	darkcore_sprite_set_x (player, _tmp2_ + ((gdouble) 32));
	_tmp3_ = darkcore_sprite_get_y (player);
	darkcore_sprite_set_y (player, _tmp3_ + ((gdouble) 100));
	darkcore_sprite_set_height (player, (gdouble) 100);
	(player->on_key_press_target_destroy_notify == NULL) ? NULL : (player->on_key_press_target_destroy_notify (player->on_key_press_target), NULL);
	player->on_key_press = NULL;
	player->on_key_press_target = NULL;
	player->on_key_press_target_destroy_notify = NULL;
	player->on_key_press = __lambda0__darkcore_sprite_delegate_type;
	player->on_key_press_target = NULL;
	player->on_key_press_target_destroy_notify = NULL;
	gee_abstract_collection_add ((GeeAbstractCollection*) engine->sprites, player);
	_tmp4_ = ball_new (&engine);
	ball = _tmp4_;
	ball_set_left_paddle (ball, player);
	gee_abstract_collection_add ((GeeAbstractCollection*) engine->sprites, (DarkcoreSprite*) ball);
	darkcore_engine_run (engine);
	result = 0;
	_g_object_unref0 (ball);
	_g_object_unref0 (player);
	_g_object_unref0 (engine);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return game_demo_main (argv, argc);
}


GameDemo* game_demo_construct (GType object_type) {
	GameDemo * self = NULL;
	self = (GameDemo*) g_object_new (object_type, NULL);
	return self;
}


GameDemo* game_demo_new (void) {
	return game_demo_construct (TYPE_GAME_DEMO);
}


static void game_demo_class_init (GameDemoClass * klass) {
	game_demo_parent_class = g_type_class_peek_parent (klass);
}


static void game_demo_instance_init (GameDemo * self) {
}


GType game_demo_get_type (void) {
	static volatile gsize game_demo_type_id__volatile = 0;
	if (g_once_init_enter (&game_demo_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GameDemoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) game_demo_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GameDemo), 0, (GInstanceInitFunc) game_demo_instance_init, NULL };
		GType game_demo_type_id;
		game_demo_type_id = g_type_register_static (G_TYPE_OBJECT, "GameDemo", &g_define_type_info, 0);
		g_once_init_leave (&game_demo_type_id__volatile, game_demo_type_id);
	}
	return game_demo_type_id__volatile;
}



